try {
    setTimeout(() => { throw 'Error!'; }, 1000);
  } catch (e) {
    console.log('에러를 캐치하지 못한다..');
    console.log(e);
  }
